### ISSUE TITLE
Sky UK - regional variation

### ISSUE THREAD

**Issue by chenks** [oe-alliance/AutoBouquetsMaker#10]
not sure if this is an ABM issue or not.
in Scotland we have BBC 2 on 115 and BBC One on 141, whereas in the rest of the UK it's the other way round.

there doesn't appear to be a way to get ABM use the scottish regional difference.

can this be changed manually via the XML file?

**Comment by AbuBaniaz** [comment]
We made them the same so that people can swap. The only way around this is to split the nations again.

**Comment by AbuBaniaz** [comment]
I'm going to close this issue. If people want to separate the providers, they should ask on forum.
