### ISSUE TITLE
hd swap exclusion- virgin cable uk ?

### ISSUE THREAD

**Issue by chenks** [oe-alliance/AutoBouquetsMaker#102]
i'm not sure if this is an issue or just the way i'm using it.
on virgin cable the sky sports HD channels are removed because they don't clear.
i have "swap HD channels" enabled, which results in the sky sports SD channels starting at 511 when they should start at 501.

is this an issue with ABM config file where SS HD channel aren't being excluded from HD swap? or is it my ABM setup?

note that there are 2 SS HD channels that do clear 509 and 510 (SS News HD and SS Mix HD).

**Comment by AbuBaniaz** [comment]
You have misunderstood.
In swaps, first number is SD, second number is HD. It will only swap if channel exists and target is in HD.

>sky sports SD channels starting at 511 when they should start at 501.
No they don't. You just asked to exclude the channel a couple of day ago. Use a mix file to move the channels or use davesayer's one

**Comment by chenks** [comment]
clearly i do misunderstand.
the HD swap is being applied the SS channes for me, even though the HD channels are excluded.

SS main event SD is channel 511 for me.
if hd swap wasn't enabled it would be at 501?

so is the HD swap being applied to this even though the HD channels are being excluded already?
isn't it a bit counter intuitive to have the channel swapped, and then have to use a mix file to undo the swap again?

**Comment by AbuBaniaz** [comment]
Enable debug in image.Enable extra debug in ABM. Run ABM for just Virgin, without swaps. Upload your debug log from image as well as Virgin example file from custom folder within ABM?

**Comment by AbuBaniaz** [comment]
There isn't even swaps for those numbers. Seek support on forum. Best you upload the debug log with your thread.

**Comment by chenks** [comment]
What forum? Didn't know you had a support forum.
No idea why my sd sky sports channels start at 511 then if no swaps are in place.

**Comment by AbuBaniaz** [comment]
They start at 511 for everyone.

**Comment by chenks** [comment]
ah ok, my mistake
