### ISSUE TITLE
Frequency wrong for 00014

### ISSUE THREAD

**Issue by lucynemzzy** [oe-alliance/AutoBouquetsMaker#105]
Hi guys the frequency is wrong for 00014

The Correct Frequency should be 378250

**Comment by AbuBaniaz** [comment]
Please run the NitAnalyser and upload the three files it creates. You will find it on a few forums.

**Comment by lucynemzzy** [comment]
I've set the correct frequency myself now by editing the xml , I was just giving you guys the heads up so you could update it in your next commit

**Comment by AbuBaniaz** [comment]
There is no correct/incorrect frequency. ABM will obtain the details from any active frequency on Cable. Your change localised change has achieved that.

It is not just the frequency, but symbol rate and modulation. Most adapted pure areas have had the frequncies with 6887 symnbol rates and QAM 64 modulation switched off. I won't be changing it unless someone provides the files from the Nit Analyser. Pure areas are self contained.

**Comment by lucynemzzy** [comment]
Ok, Well I have searched for that file and can't find it, so if you could link me it I'll happily run it for you bud to provide you with the stuff you need

**Comment by lucynemzzy** [comment]
[nit.log](https://github.com/oe-alliance/AutoBouquetsMaker/files/2842718/nit.log)

**Comment by lucynemzzy** [comment]
Here is the files you requested,

Hopefully you'll see now what the correct Freq should be

[files.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/2842722/files.zip)
