### ISSUE TITLE
ABM Hides Bouquets that are Folders within Folders

### ISSUE THREAD

**Issue by ian10951** [oe-alliance/AutoBouquetsMaker#106]
If a Bouquet is used that has folders within folders in it to keep certain things tidy, ie 1:7:1 reference inside the Bouquet, then when this none ABM Bouquet is selected for saving, ABM hides it by adding 519 to it in the Bouquets.tv file, even though its been instructed to save and not hide.

**Comment by ian10951** [comment]
Anyone have any thoughts on this ?

Its a real pain having to edit the Bouquets.tv file after each and everytime ABM is ran, to get these Bouquets back again.

**Comment by AbuBaniaz** [comment]
Can you upload bouquets that are being affected. Edit out anything sensitive please.

**Comment by ian10951** [comment]
Attached is a bouquet created for use just on our Tvheadend Server. The Bouquet has folders within folders to keep things neat and sepearate from the main Bouquets list used on the Server. This Bouquet is required because of the limitations of Enigma2 when you wish to Record as E2 cannot record if using 5002. So this bouquet is a dupe of the other Bouquets, but flagged as 1 so E2 can record from the Server.

[userbouquet.Ouriptv.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/2847974/userbouquet.Ouriptv.zip)

**Comment by Huevos** [comment]
Please provide a list of steps (not a description) to simulate this condition. What do you mean "selected for saving"? Please take a screengrab of you config.

**Comment by ian10951** [comment]
Its the same result using either way of saving the none ABM Bouquets, the Bouquets containing Sub Folders are always hidden rather than saved, and to get them back the Bouquets.tv file has to be edited, removing the 519 that ABM has placed against the Bouquet and replacing it with 7
![1_0_19_28a7_68_f020_ffff0000_0_0_0_20190212072813](https://user-images.githubusercontent.com/11910714/52619027-71c2a880-2e98-11e9-897d-07888c780ae4.jpg)
![1_0_19_28a7_68_f020_ffff0000_0_0_0_20190212072927](https://user-images.githubusercontent.com/11910714/52619035-78e9b680-2e98-11e9-883a-df0b151e07c9.jpg)
![1_0_19_28a7_68_f020_ffff0000_0_0_0_20190212072852](https://user-images.githubusercontent.com/11910714/52619040-7dae6a80-2e98-11e9-9a0e-65262ad3c369.jpg)


.

**Comment by AbuBaniaz** [comment]
The bouquet you uploaded is incomplete.

**Comment by ian10951** [comment]
In what way ?

Of course you wont be able to open the sub folders as you do not have the py files to generate those Bouquets, nor do you have connection to the TvHeadend Server.

The Bouquet was just an example of the problem. Just load it and then save it in ABM then run ABM and you will see its no longer in your Bouquets lst and is hidden in your Bouquets.tv file. Forget about being able to open the Sub Bouquets, you dont need to.

**Comment by ian10951** [comment]
@AbuBaniaz 

Thanks for the fix, Evo sent it to me on Slype and it was waiting for me when I signed in this morning.
All tested and working so you can close this issue now when your ready.

Cheers buddy.

**Comment by Huevos** [comment]
Thanks Huevos for taking the time to fix this.

**Comment by AbuBaniaz** [comment]
@Huevos has fixed this.

**Comment by Huevos** [comment]
https://github.com/oe-alliance/AutoBouquetsMaker/commit/f4643e7e78ec638a02ab80c08962185b23bd0e3d
