### ISSUE TITLE
failed to tune virgin uk on tuner c

### ISSUE THREAD

**Issue by boadi** [oe-alliance/AutoBouquetsMaker#108]
Pls I have upgraded the zgemma h3.2tc with the latest firmware. I have tried to scan VM channels with AUTOBOUQUESMAKER BUT I GET THE BELOW ERROR MESSAGE. PLS I NEED TO SORT IT OUT. PLS I AM IN LEEDS
 AND NETID IS 41053

failed to tune virgin uk on tuner c

**Comment by AbuBaniaz** [comment]
The frequency we have in ABM is correct as far as we know. I just run the NitAnalyser and teh same details were returned.  You need to look at your signal levels and connections.

**Comment by davesayers2014** [comment]
Im using netid 41053 without issues

**Comment by boadi** [comment]
Thanks. I think I am having issues the signal. Pls is there any way I can sort the signal problem

**Comment by paramdeep10** [comment]
Hello. I'm using the H5 2TC and i'm getting "Failed tot tune Virgin (UK) on tuner C. Please check the tuner is correctly configured." The setup is correct. I'm in Leicester 00012. It was working fine before but no longer scans. Any help would be appreciated. Thanks.

**Comment by AbuBaniaz** [comment]
Have you updated the provider file?

**Comment by paramdeep10** [comment]
Thanks for replying. I haven't. Is that the config file or something else? I tried to update that but had a message pop up saying incompatible versions 2.8>3.1.

**Comment by AbuBaniaz** [comment]
Install  latest ABM or update your image.

**Comment by paramdeep10** [comment]
thanks. will give it a go and see if that works.

**Comment by paramdeep10** [comment]
Updated my openatv to 6.2 and then installed ABM. Everything is working again. Thank you for your help.

**Comment by boadi** [comment]
Thank. Issue solved
