### ISSUE TITLE
Update 00015 Lichfield 

### ISSUE THREAD

**Issue by IL1981** [oe-alliance/AutoBouquetsMaker#111]
Hi Abu, been a while since I posted on wos but you fixed it then when an update was required before to my area, getting tuner lock now everything latest updateand had a read around saying 6887 is being phased out. Managed a manual scan just and confirm 6952 is the change, the frequency the same and QAM256.   I wasn't able to upload a log as without my laptop so hopefully this is enough, thanks.

**Comment by AbuBaniaz** [comment]
I have added details you have mentioned for now. Can you run the NitAnalyser tool when you get a moment just to double check. Will take about 25 minutes in a Pure area.

**Comment by IL1981** [comment]
Sure, will do this over next weekend, thanks
