### ISSUE TITLE
Not adding ROK+1 and strange channels in Sport bouquest

### ISSUE THREAD

**Issue by escortrs** [oe-alliance/AutoBouquetsMaker#112]
Hi,

Can you help me with some issues,

1)After a scan with autobouquestmaker, it does not add channel ROK+1 (it scans and finds it) to Movies bouquest, ROK is there but not ROK+1. I can add it manually but at the next scan it will be missing again.

2)In the Sport bouquest it adds channels, FAMEtv, YANGA, ait International, abn tv and BBC Scotland, None of these are sports channels.

Any help would be great.

Kind regards.

**Comment by AbuBaniaz** [comment]
Thanks for reporting, we will look into issue

**Comment by AbuBaniaz** [comment]
ABM uses the number to place services in bouquets. The bouquets are divided into number ranges.

If you look at the official receiver, you will find that the issue you have reported is also present in the "all channels" bouquet.
![sky_all_channels_1](https://user-images.githubusercontent.com/6644489/60839641-8dbb4380-a1c5-11e9-9390-1df909cda01c.jpg)
![sky_all_channels_2](https://user-images.githubusercontent.com/6644489/60839652-957ae800-a1c5-11e9-99a6-c949bef4bc85.jpg)

The subsequent bouquets do not have these.
![sky_sports_1](https://user-images.githubusercontent.com/6644489/60839665-9c095f80-a1c5-11e9-9af5-b75ddf7b07f4.jpg)
![sky_sports_2](https://user-images.githubusercontent.com/6644489/60839666-9dd32300-a1c5-11e9-98a4-a31d32a9debd.jpg)

This is the same problem as when they had the news/documentary overspill.

It is possible to get this to work properly, but people get hangups about numbers. Enigma2 does not have fixed numbering. It is dynamic and based on settings, order in which services were loaded and as well as the bouquet from which the service was selected.

Anyway, you have to use a favourites.xml file. You can place services in your chosen bouquets.
