### ISSUE TITLE
T2MI

### ISSUE THREAD

**Issue by Huevos** [oe-alliance/AutoBouquetsMaker#117]
Add compatibility for reading/writing T2MI data in lamedb.

https://github.com/OpenPLi/enigma2/commit/941f2f119ef5666e13a0271ff9c366f8f6b23e15

**Comment by AbuBaniaz** [comment]
Do we close now?
https://github.com/oe-alliance/AutoBouquetsMaker/commit/b0d10883125240e66401ce63548e947c7db92291

**Comment by Huevos** [comment]
Yes. Was just a reminder for me.
