### ISSUE TITLE
UK Virgin Cable - HD Channel Swap

### ISSUE THREAD

**Issue by chenks** [oe-alliance/AutoBouquetsMaker#120]
Hi, the HD channel swap for Alibi HD is currently broken due to the virgin changin the channel number a few days ago.

the HD swap now puts Drama +1 on 126
Alibi HD has moved to 212 and Drama +1 has launched on 226 (Alibi HD was previously on 226)

**Comment by jenseneverest** [comment]
yes it looks like there will have to be a reshuffle, adding the full list for ref purposes

Entertainment:
000. Live Events Channel (NOT on TiVo or V6 Boxes)
100. Virgin Media Showcase
101. BBC ONE (England only)
101. BBC ONE Scotland HD (Scotland only)
101. BBC ONE Northern Ireland HD (Northern Ireland only)
101. BBC ONE Wales HD (Wales only)
102. BBC TWO England HD (England and Scotland only)
102. BBC TWO Scotland (Scotland only)
102. BBC TWO Northern Ireland HD (Northern Ireland only)
102. BBC TWO Wales HD (Wales only)
103. ITV (England and Wales only)
103. STV HD (Scotland only)
103. UTV (Northern Ireland only)
104. Channel 4 (Outside London)
104. Channel 4 HD (London only)
105. Channel 5
106. E4
107. BBC FOUR HD
108. BBC ONE London HD (England only)
108. BBC Scotland HD (Scotland only)
109. Sky One HD
110. Sky One
111. Sky Witness HD
112. Sky Witness
113. ITV HD (England and Wales only)
113. UTV HD (Northern Ireland only)
114. ITV +1 (England and Wales only)
114. STV +1 (Scotland only)
114. UTV +1 (Northern Ireland only)
115. ITV2
116. ITV2 +1
117. ITV3
118. ITV4
119. ITVBe
120. ITVBe +1
121. Sky Two
122. Sky Arts
123. Pick
124. GOLD HD
125. W
126. Alibi
127. Dave
128. Really
129. YESTERDAY
130. Drama
131. Dave ja vu
132. Comedy Central
133. Comedy Central +1
134. MTV
135. SYFY
136. SYFY +1
137. Universal TV
138. Universal TV +1
139. Challenge
140. Sky Witness +1
141. Channel 4 HD (Outside London)
142. Channel 4 +1
143. 4Seven
145. E4 HD
146. E4 +1
147. More4
148. CBS Reality
149. horror channel
150. Channel 5 HD
151. 5STAR
152. 5SELECT
153. 5 USA
154. 5Spike
155. Channel 5+1
156. E!
157. FOX
158. FOX+1
159. For full list of Local channels on Virgin Media see - Local TV:
160. Real Lives
161. BBC ALBA (Red Button for English audio on Live Sports)
162. BBC Scotland HD (England, Wales and Northern Ireland only)
164. Universal TV HD
165. SYFY HD
166. S4C HD (Red Button for English and Welsh audio)
167. TLC
168. TLC HD
169. TLC+1
170. I.D.
171. I.D.+1
172. Quest
173. Quest +1
174. ITV3 +1
175. ITV4 +1
176. ITV2 HD
177. ITV3 HD
178. ITV4 HD
179. ITVBe HD
180. Challenge +1
181. Comedy Central HD
182. Comedy Central Extra
183. MTV HD
184. BET
185. 5 USA +1
186. 5STAR +1
187. Paramount Network HD
188. Paramount Network
189. Sony Channel
190. W +1.
191. Alibi +1
192. CBS Justice
193. Sony Crime Channel
194. GOLD +1
195. More 4 HD
196. More 4 +1
197. CBS Drama
198. YouTube (Only on TiVo or V6 Boxes)
199. FOX HD
200. YESTERDAY +1
201. CBS Reality +1
202. horror channel +1
203. 4Seven HD
204. Netfilx (Only on TiVo or V6 Boxes)
205. Virgin TV Ultra HD (Only on V6 Boxes).
206. Sky Arts HD
207. Real Lives+1
208. Lifetime HD
209. Crime + Investigation HD
210. hayu (Only on TiVo or V6 Boxes)
211. W HD
212. Alibi HD
213. DMAX
214. DMAX +1
215. Quest Red
216. Blaze
217. Quest HD
218. Your TV
219. Vice
220. Sony Channel +1
222. Crime + Investigation +1
226. Drama +1
227. Dave HD
228. Prime Video (Only on V6 Boxes).
229. E! HD

Local TV:
The following channels are only in some areas:
159. London Live (In Bromley, Croydon, Haringey, Hayes, Hersham, Lewisham, Seven Kings and Watford areas only.)
159. NOTTS TV (In Nottingham areas only.)
159. Latest TV (In Sussex areas only.)
159. SLTV (In Sheffield and Rotherham areas only.)
159. NVTV (In Belfast areas only).
159. Bristol TV (In Bristol areas only).
159. Cardiff TV (In Cardiff areas only).
159. Leeds TV (In Kirklees and Leeds areas only).
159. Tyne and Wear TV (In Gateshead and Wearside areas only).
159. Liverpool TV (In Liverpool, Wirral, Warrington, Burnley and Preston (part) areas only).
159. That's TV Norfolk (In Norwich areas only).
159. Birmingham TV (In Birmingham and Wolverhampton areas only).
159. That's TV Cambridge (In Cambridge areas only).
159. That's TV Swansea Bay (In Swansea areas only).
159. Teesside TV (In Teeside areas only).
159. KMTV (In Ashford, Basildon and Crawley areas only).
159. That's TV Humber (In Grimsby areas only).

Factual & Lifestyle:
245. Eden
246. Eden +1
247. Eden HD
250. Discovery Channel
251. Discovery HD
252. Discovery Channel +1
256. Animal Planet
257. Animal Planet HD
258. Animal Planet +1
259. Discovery Science
260. Discovery Science +1
261. Discovery Turbo
262. Discovery History
263. Discovery History +1
264. Nat Geo WILD
265. Nat Geo WILD HD
266. National Geographic
267. National Geographic +1
268. National Geographic HD
269. Together TV
270. HISTORY HD
271. HISTORY +1
273. HISTORY 2 HD
276. PBS America
277. Forces TV
281. Home
282. Home +1
284. Home & Health
285. Home & Health +1
286. Discovery Shed
287. God Channel
291. Food Network
292. Travel Channel
293. Love Nature HD
294. Love Nature
295. Smithsonian Channel HD
298. Horse + Country

Music:
300. New Music on Demand (Only on TiVo or V6 Boxes)
310. MTV MUSIC
311. MTV Live HD
312. MTV HITS
313. MTV BASE
314. Club MTV
315. MTV ROCKS
316. VH1
318. MTV OMG
330. Box Upfront
335. The Box
336. Box Hits
337. 4Music
338. Kiss 
340. Magic
342. Kerrang
344. Vevo (Only on TiVo or V6 Boxes)
345. Clubland TV
346. NOW 80s
347. NOW 90s
348. Total Country  

Movies:
400. Virgin Movies & Store (Only on TiVo or V6 Boxes)
401. Sky Cinema Premiere HD (Only on TiVo or V6 Boxes)
402. Sky Cinema Select HD (Only on TiVo or V6 Boxes)
403. Sky Cinema Hits HD (Only on TiVo or V6 Boxes)
404. Sky Cinema Greats HD (Only on TiVo or V6 Boxes)
405. Sky Cinema Disney HD (Only on TiVo or V6 Boxes)
406. Sky Cinema Family HD (Only on TiVo or V6 Boxes)
407. Sky Cinema Action & Adventure HD (Only on TiVo or V6 Boxes)
408. Sky Cinema Comedy HD (Only on TiVo or V6 Boxes)
409. Sky Cinema Crime & Thriller HD (Only on TiVo or V6 Boxes)
410. Sky Cinema Drama & Romance HD (Only on TiVo or V6 Boxes)
411. Sky Cinema Sci-Fi & Horror HD (Only on TiVo or V6 Boxes)
412. Sky Cinema Premiere +1 (Only on TiVo or V6 Boxes)
415. TCM Movies
416. TCM Movies HD
417. TCM Movies +1
419. Movies 24
420. Movies 24 +
424. Sony Movies Classic
425. Sony Movies
426. Sony Movies Action
428. Film4
429. Film4 HD
430. Film4 +1
445. Talking Pictures TV

Sport:
501. Sky Sports Main Event HD (Only on TiVo or V6 Boxes)
502. Sky Sports Premier League HD (Only on TiVo or V6 Boxes)
503. Sky Sports Football HD (Only on TiVo or V6 Boxes)
504. Sky Sports Cricket HD (Only on TiVo or V6 Boxes)
505. Sky Sports Golf HD (Only on TiVo or V6 Boxes)
506. Sky Sports F1 HD (Only on TiVo or V6 Boxes)
507. Sky Sports Action HD (Only on TiVo or V6 Boxes)
508. Sky Sports Arena HD (Only on TiVo or V6 Boxes)
509. Sky Sports News HD (Only on TiVo or V6 Boxes) 
510. Sky Sports Mix HD (Only on TiVo or V6 Boxes) 
511. Sky Sports Main Event (Only on TiVo or V6 Boxes)
512. Sky Sports Premier League (Only on TiVo or V6 Boxes)
513. Sky Sports Football (Only on TiVo or V6 Boxes)
514. Sky Sports Cricket (Only on TiVo or V6 Boxes)
515. Sky Sports Golf (Only on TiVo or V6 Boxes)
516. Sky Sports F1 (Only on TiVo or V6 Boxes)
517. Sky Sports Action (Only on TiVo or V6 Boxes)
518. Sky Sports Arena (Only on TiVo or V6 Boxes)
519. Sky Sports News
520. Sky Sports Mix
521. Eurosport 1 HD
522. Eurosport 2 HD
523. Eurosport 1
524. Eurosport 2
526. MUTV
527. BT Sport 1 HD [BT Sport Extra Channels via Red Button]
528. BT Sport 2 HD [BT Sport Extra Channels via Red Button]
529. BT Sport 3 HD [BT Sport Extra Channels via Red Button]
530. BT Sport ESPN HD [BT Sport Extra Channels via Red Button]
531. BT Sports Ultimate (Only on V6 Boxes).
535. Sky Sports Racing
536. Racing TV HD
544. Liverpool FC TV HD
546. Box Nation
551. Premier Sports 1 HD
552. Premier Sports 2 HD
553. FreeSports HD

News:
601. BBC NEWS HD
602. Sky News
603. Sky News HD
605. BBC Parliament
607. CNN International
609. Bloomberg Television HD
613. CNBC
620. euronews
621. NDTV 24x7
622. Al Jazeera English
624. France 24 English HD
625. NHK World Japan

Kids:
700. Kids TV on Demand (Only on TiVo or V6 Boxes)
701. CBBC Channel HD
702. CBeebies HD
703. Baby TV
704. Cartoon Network
705. Cartoon Network +1
706. Cartoonito
707. Disney XD
712. Nickelodeon
713. Nick +1
714. Nick HD
715. Nick Junior
716. Nick Jr Too
717. Nicktoons
724. Disney Channel
725. Disney Channel +1
727. Disney Junior
730. Boomerang
731. Boomerang +1
732. Cartoon Network HD
734. CITV
736. POP
737. Tiny Pop
739. ZooMoo HD


Shopping:
740. QVC
741. QVC Beauty
742. QVC Style
747. Ideal World
748. Create & Craft
755. Gems TV
756. Jewellery Maker
757. TJC

International:
800. Desi Entertainment (Only on V6 Boxes).
801. Star Gold HD
802. Star Bharat
803. Star Plus HD
805. SONY TV HD
806. SONY MAX HD
807. SONY SAB
809. Zee TV
810. Zee Cinema HD
815. B4U Movies
816. B4U Music
826. COLORS
827. Colors Rishtey
828. Colors Cineplex
829. NDTV Good Times
831. Al Jazeera Arabic
832. France 24 (French) HD
833. HUM EUROPE
836. NDTV India
837. NDTV Spice
838. Islam Channel English
839. Islam Channel Urdu
840. Brit Asia TV
841. MTV Beats

Regions and Audio Description:
851. BBC ONE London AD (Audio description)
852. BBC TWO AD (Audio description)
853. ITV AD (Audio description)
854. Channel 4 AD (Audio description)
855. Channel 5 AD (Audio description)
856. S4C AD (Audio description - Red Button for English and Welsh audio)
858. BBC ONE (Alternative regional variation, select regions only)
861. BBC ONE London
862. BBC ONE Scotland
863. BBC ONE Northern Ireland
864. BBC ONE Wales
865. BBC TWO England
870. ITV (Alternative regional variation, select regions only)
871. ITV (Alternative regional variation, select regions only)
875. RTÉ One (Northern Ireland only)
876. RTÉ 2 (Northern Ireland only)
877. TG4 (Northern Ireland only)

Radio:
901. BBC Radio 1
902. BBC Radio 2
903. BBC Radio 3
904. BBC Radio 4 FM
905. BBC Radio 5 Live
906. BBC World Service
907. BBC Radio 1 Xtra
908. BBC Radio 5 Live Sports Extra
909. BBC Radio 6 Music
910. BBC Radio 4 Extra
911. BBC Radio 4 LW
912. BBC Asian Network
913. BBC Radio Cymru 2
915. Absolute Radio
916. Smooth Radio
917. RTÉ Radio
918. Heart
919. LBC
920. World Radio Network (WRN Radio)
921. Heart 80s
922. Classic FM
923. Gold Radio
924. Planet Rock
927. talkSPORT
928. Magic Radio
930. BBC Radio Scotland
931. BBC Radio Wales
932. BBC Radio Ulster
933. BBC Radio Foyle
934. BBC Radio nan Gàidheal
936. BBC Radio Cymru
937. BBC Radio London
951. Absolute 80s
952. Absolute Classic Rock
958. Capital
959. Capital XTRA
960. Radio X
963. Kiss FM

Help and Information:
968. A Message For Parents

Adult:
969. Adult Previews
970. Television X Nightly
971. Babes & Brazzers TV Nightly
972. Adult Channel Nightly
973. XXX Brits Nightly
974. Xrated 40+ Nightly
976. Bangers Nightly
978. Television X
979. XXX Brits
980. Adult Channel
981. Babenation (Viewers need PIN number to view from 6am to 10pm.)
982. Meets The Babes (Viewers need PIN number to view from 6am to 10pm.)
983. Pure Babes HD Nightly

Help and Information:
985. A Message For Parents

Red Button Channels:
991. BBC Red Button 1

Welcome and Information:
997. Virgin TV For Newbies
998. Virgin Media What's On

Ultra HD:
999. Virgin TV Ultra HD (Only on V6 Boxes).

**Comment by chenks** [comment]
you've marked the Sky Cinema HD channels as "(Only on TiVo or V6 Boxes)", but they still clear fine on non TiVo/V6 boxes.

**Comment by AbuBaniaz** [comment]
Please post something that does not have to be investigated/deciphered. E.g please change this swap
```
		<channel number="118" with="178" /><!-- ITV4 HD -->
```
to
```
		<channel number="118" with="245" /><!-- ITV4 HD -->
```

**Comment by chenks** [comment]
126 needs to be swapped with 212
it is currentlly being swapped incorrectly to 226

**Comment by jenseneverest** [comment]
> you've marked the Sky Cinema HD channels as "(Only on TiVo or V6 Boxes)", but they still clear fine on non TiVo/V6 boxes.

i know what works, that is not my list just a copy and paste for ref purposes.

**Comment by jenseneverest** [comment]
UPDATED: More Channels moves confirmed for Tuesday
More Discovery and Sky Channels are set to move on Tuesday (October 1st)
ID moves to Channel 168.
Quest HD moves to Channel 169.
Quest Red moves to Channel 170.
DMAX moves to Channel 171.
Animal Planet HD moves to Channel 251.
Discovery Science moves to Channel 252.
Discovery Turbo moves to Channel 256.
Discovery History moves to Channel 257.
Discovery History +1 moves to Channel 261.
Home moves to Channel 279.
Discovery Home & Health moves to Channel 280.
Discovery Shed moves to Channel 281.
Food Network moves to Channel 278.
Travel Channel moves to Channel 282.
Also:
-Sky News HD moves to Channel 602.
-Sky News SD moves to Channel 603.

**Comment by AbuBaniaz** [comment]
We did not add the swaps where the channels are next to each other, so should not be too significant a change for swaps

**Comment by chenks** [comment]
the swap for 172 now needs removed as the HD version is now on 172.
the swap for 167 now needs removed as the HD version is now on 167.

jensens update above it wrong for some channels.
Discovery Channel HD has moved from Virgin UK Channel 257 to Virgin UK Channel 256.
Animal Planet HD has moved from Virgin UK Channel 251 to Virgin UK Channel 250.
both those are the opposite. Discovery HD is now 250 and AP HD is now 256

**Comment by jenseneverest** [comment]
> the swap for 172 now needs removed as the HD version is now on 172.
> the swap for 167 now needs removed as the HD version is now on 167.
> 
> jensens update above it wrong for some channels.
> Discovery Channel HD has moved from Virgin UK Channel 257 to Virgin UK Channel 256.
> Animal Planet HD has moved from Virgin UK Channel 251 to Virgin UK Channel 250.
> both those are the opposite. Discovery HD is now 250 and AP HD is now 256

read carefully, those changes are yet to happen. They will on the 1/08/2019. Next Tuesday
No point updating it until virgin finish moving things about

**Comment by chenks** [comment]
the EPG for me is currently saying they have been moved
251 is now called "channel update" and the EPG data says "discovery HD now on 250".

**Comment by AbuBaniaz** [comment]
Is that in an official box or bouquets that were previously created by ABM?

**Comment by chenks** [comment]
bouquets created by ABM, using your newest file from 10 minutes ago (with the HD swap enabled).
