### ISSUE TITLE
Cannot read data

### ISSUE THREAD

**Issue by ikosk** [oe-alliance/AutoBouquetsMaker#127]
I am testing a new provider at 16 ° E and AMB reports an error: Cannot read data

It is a transponder with a frequency: 11 283 MHz.

Where is the problem?

[sat_160_test_11283.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3890845/sat_160_test_11283.txt)

[ts_data_xml.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3890853/ts_data_xml.txt)

**Comment by Huevos** [comment]
Please provide a debug log with extra debug enabled.

**Comment by ikosk** [comment]
Log.

[debug.log](https://github.com/oe-alliance/AutoBouquetsMaker/files/3900994/debug.log)
