### ISSUE TITLE
UK Virgin Cable - HD Channel Swap

### ISSUE THREAD

**Issue by chenks** [oe-alliance/AutoBouquetsMaker#134]
there has been a slight channel shuffled again which may affect the HD swap

Channel 5 HD is now on 105 / Channel 5 SD is now on 154 (HD swap can now be removed for this channel)
Paramount HD is now on 150 (previously on 187) - however i don't believe a swap was in place for this channel anyway.

**Comment by AbuBaniaz** [comment]
This will be the same as the BBC2/Channel 4 changes while the SD channel is phased out.

As mentioned several times, swap only takes place if the target is HD.
