### ISSUE TITLE
add LaLiga 28.2

### ISSUE THREAD

**Issue by babis20** [oe-alliance/AutoBouquetsMaker#136]
hello, can you please add LaLiga for sky uk sports 28.2e
11426 V 29500 8/9 QPSK

also Colours Hd under international 28.2e 
11686 V 23000 2/3 8psk

Thanks

**Comment by AbuBaniaz** [comment]
Please re-explain what you mean.  Using an SD channel list, the current situation is:
La Liga HD = 435
Colors = 706
Colors HD = 884

**Comment by AbuBaniaz** [comment]
I have worked out that you meant that they are viewable and wanted them to be whitelisted.

Please update your ABM provider files.
