### ISSUE TITLE
Getting a crash at the Bouquet creation stage after the latest update

### ISSUE THREAD

**Issue by ian10951** [oe-alliance/AutoBouquetsMaker#137]
Using ATV 6.3

17:26:26.5855 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-02-23 17:26:26+0000 [-] [ABM-BouquetsWriter] Writing lamedb...
17:26:26.5884 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-02-23 17:26:26+0000 [-] Traceback (most recent call last):
17:26:26.5890 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-02-23 17:26:26+0000 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/main.py", line 490, in doBuildIndex
17:26:26.6017 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-02-23 17:26:26+0000 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/manager.py", line 102, in save
17:26:26.6025 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-02-23 17:26:26+0000 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/bouquetswriter.py", line 40, in writeLamedb
17:26:26.6044 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-02-23 17:26:26+0000 [-]     if transponder["modulation_system"] == 0: # DVB-S
17:26:26.6051 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-02-23 17:26:26+0000 [-] KeyError: 'modulation_system'
17:26:26.6053 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method AutoBouquetsMaker.doBuildIndex of <class 'Plugins.SystemPlugins.AutoBouquetsMaker.scanner.main.AutoBouquetsMaker'>>,()) failed)

**Comment by Huevos** [comment]
Why are you mixing files from different versions?
