### ISSUE TITLE
FastScan problem

### ISSUE THREAD

**Issue by ikosk** [oe-alliance/AutoBouquetsMaker#138]
After the last update is a problem with Fastscan. Blue screen. Send log.
[enigma2_crash_1584685666.log](https://github.com/oe-alliance/AutoBouquetsMaker/files/4358216/enigma2_crash_1584685666.log)

**Comment by Huevos** [comment]
Thanks for reporting.

https://github.com/oe-alliance/AutoBouquetsMaker/commit/23239581017e1b689255f19665015b3212bc65b3

Should be fixed with that change.

**Comment by AbuBaniaz** [comment]
@ikosk 
Please close when happy with this fix

**Comment by ikosk** [comment]
Solved.
