### ISSUE TITLE
TG4 added to Pick+ 1 position 

### ISSUE THREAD

**Issue by davesayers2014** [oe-alliance/AutoBouquetsMaker#14]
Hi I was looking at the channel changes that are happening on 5th of JanuaryDiscovery Shed moves from 242 to 161 , Home & Health moves from 240 to 162 and Home & Health + 1 moves from 241 to 240 so the RTE channels will need moving in the channels to add by Id. 

While looking I noticed TG4 is added to 163 via add by Id but 163 is pick+ 1

channels_to_add_by_id = {
		1251: 161, # RTE One
		1252: 162, # RTE2
		1253: 163, # TG4

Possible solution is to move them to 283  onwards

**Comment by AbuBaniaz** [comment]
Thanks for reporting. We'll look at it after the changes.
