### ISSUE TITLE
DMAX+1 not showing in Bouquet

### ISSUE THREAD

**Issue by escortrs** [oe-alliance/AutoBouquetsMaker#143]
Hello Everyone,

I have noticed that DMAX+1 does not show in any bouquet apart from Last Scanned, Its not in All Channels or Plus 1, I have been adding it to both bouquets manually, Can this be changed?

Many thanks for you work.

**Comment by AbuBaniaz** [comment]
It is on 272 on HD lineup

**Comment by escortrs** [comment]
Hello,

Thanks for the reply, It does not appear in my HD bouquet or any other bouquet, I cannot see it in any of them. 
I am in the UK an my setting for AutoBouquetsMaker are

Freesat UK = no
Sky ROI = no
Sky UK = yes
Region = Essex SD Custom
FTA only = yes
Create main bouquet = yes(all channels)
Create sections bouquets = yes
Create HD bouquet = yes
Swap channels = no

I dont know if my setting are wrong?

Thank you

**Comment by AbuBaniaz** [comment]
You have the FTA scan only set. The channel is marked as NOT being FTA, even though it is. You will see a card icon on the infobar. This is why it is missed. We shall modify the flag so that ABM treats it as FTA.

**Comment by AbuBaniaz** [comment]
I have added the hack. Update the provider file, do not change the ABM settings, run ABM again.

I'll close the issue now. Post back if there is a problem
