### ISSUE TITLE
Unable to get Russian provider Hotbird 13E

### ISSUE THREAD

**Issue by RoundTriangle** [oe-alliance/AutoBouquetsMaker#145]
I've got a single satellite pointing at Hotbird 13E to pick up Russian channels for my partner. I can see providers such as Sky Italia, BIS TV and Com Hem; but I can't see a provider for Russian TV Channels.

Can the appropriate provider be added for Russian TV Channels?

**Comment by AbuBaniaz** [comment]
What is the name of the provider? Do you have details of the home frequency they use?

**Comment by JoeJenningsDMC** [comment]
Here's what I'm using as a channel list at the moment: http://en.satexpat.com/tv/russia/#wrapper - Frequencies and such are listed there.

I'm going into Openwebif on my Zgemma box and searching for the names listed on that page.

**Comment by RoundTriangle** [comment]
Here's what I'm using as a channel list at the moment: http://en.satexpat.com/tv/russia/#wrapper - Frequencies and such are listed there.

I'm going into Openwebif on my Zgemma box and searching for the names listed on that page.

**Comment by AbuBaniaz** [comment]
This plugin reads the tables from the provider. I cannot find the details of the provider on that link. If you can find the details of the provider/broadcaster, we can try and assist.

Otherwise, you may find it easier for someone to maintain a channel list that others can download.
