### ISSUE TITLE
New channels

### ISSUE THREAD

**Issue by krisawatson** [oe-alliance/AutoBouquetsMaker#146]
New channels add for UK Sky and UK Virgin Media.
Sky Documentaries (Sky channel 114 and VM 277) and Sky Nature (Sky 130 and VM 279) are new channels added as of 27th May.

**Comment by AbuBaniaz** [comment]
We don't add channels manually, the list is created using the data the provider has.

What is the issue you are experiencing?

**Comment by krisawatson** [comment]
I guess the problem is the data providers are not up to date then.  Sky has introduced 2 new channels and they are not appearing.

**Comment by AbuBaniaz** [comment]
They are appearing for me. Below taken from the example file after running with London SD. The channels are on the blacklisted transponders so will be skipped when using the custom hacks mode/area selection. 

```
<configuration lcn="114" channelnumber="114" description="SkyDocumntrs"></configuration>
<configuration lcn="130" channelnumber="130" description="Sky Nature"></configuration>
<configuration lcn="814" channelnumber="814" description="SkyDocmntrsHD"></configuration>
<configuration lcn="893" channelnumber="893" description="Sky Nature HD"></configuration>
```
