### ISSUE TITLE
PICK republic of Ireland

### ISSUE THREAD

**Issue by escortrs** [oe-alliance/AutoBouquetsMaker#150]
Hi,
Sorry to mention PICK TV again but I updated to your latest version and rescanned and noticed that even when set to the correct region of the UK, AutoBouquets is putting the Republic of Ireland version into the All Channels Bouquet and not the UK version, I only noticed because all the prices in the adverts are in Euros not GB Pounds. I found the UK version and swapped them over.  The UK version has a different service ref to the Irish version
1:0:1:16C4:7DB:2:11A0000:0:0:0::Pick             UK version

1:0:1:159A:7E7:2:11A0000:0:0:0:                     Irish Version

Also, Where can I find the forum for AutoBouquetsMaker?

Thank you for your time.

**Comment by AbuBaniaz** [comment]
There isn't a forum for autobouquetsmaker.  Start a thread on world of satellite, linuxsat, techkings, digitalworldz with your debug log. You are doing/expecting something wrong.
