### ISSUE TITLE
Channel is missing when doing a channelscan

### ISSUE THREAD

**Issue by retrofan1979** [oe-alliance/AutoBouquetsMaker#157]
Hi, I'm doing a DVB-C channelscan, but the channellist misses one channel. When doing a channelscan with TransEdit the LCN is filled in with channelnumber 613 which is correct. How can I get this missing channel with AutoBouquetsMaker?

**Comment by retrofan1979** [comment]
AutoBouquetsMaker doesn't show channel 613 in the channellist like a normal TV set even though the LCN seems to exist.
Can we debug this please and how?

**Comment by retrofan1979** [comment]
I also tried the cableplugin from the feed, and this one finds channel 613 without problems.

However, I need AutoBouquetsMaker as the cablescan plugin doesn't work with SAT>IP server like AutoBouquetsMaker does.

Can you please fix this issue?

Thanks!

**Comment by AbuBaniaz** [comment]
Enable debug logs in image. Enable extra debug in ABM. Run ABM just for that provider and then upload debug log. If you have IPTV, delete any sensitive details.

If you can get a stream recording of the raw data on the home transponder, even better. About 60seconds worth is long enough.

**Comment by retrofan1979** [comment]
[Ziggo-former UPC-4444 164 08-10 15-36-44.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/5051107/Ziggo-former.UPC-4444.164.08-10.15-36-44.zip)
Which program can I use? TransEdit? I will also try to upload the debug logs later this day.

**Comment by retrofan1979** [comment]
Here's the debug log:

[Enigma2-debug-20200810_16-15-49.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/5051371/Enigma2-debug-20200810_16-15-49.zip)

**Comment by retrofan1979** [comment]
Hmmm, the service name for channel 613 has an additional space
Also an error which isn't the same as the others in the log: not in service_dict_tmp
Maybe if we can remove the space in the servicename this issue is fixed?

16:17:27.9875 {   } Plugins/SystemPlugins/AutoBouquetsMaker/scanner/dvbscanner.py:651 updateAndReadServicesLCN [ABM-DvbScanner] SDT service {'region_code': 255, 'free_ca': 0, 'service_name': 'Stingray Classica ', 'service_group_id': 0, 'logical_channel_number': 613, 'original_network_id': 1536, 'service_id': 20044, 'service_type': 1, 'transport_stream_id': 2051, 'provider_name': 'Ziggo', 'category_id': 0, 'bouquets_id': 0, 'city_code': 65535}
16:17:27.9880 {   } Plugins/SystemPlugins/AutoBouquetsMaker/scanner/dvbscanner.py:663 updateAndReadServicesLCN [ABM-DvbScanner] Stingray Classica  not in service_dict_tmp

**Comment by retrofan1979** [comment]
I hope you can fix this. Please let me know.

**Comment by retrofan1979** [comment]
Is the debug file useful for you?

**Comment by retrofan1979** [comment]
I don't see the problem as the LCN is found and has number 613. However the channel is not added to the channellist as it should be.
Can you please fix this somehow? Thank you!

**Comment by retrofan1979** [comment]
I also did a channelscan with another network ID from my provider. Now channel 613 isn't skipped and shows up in the channellist. However, I cannot use this other network ID because I don't have a subscription of most channels, only a few which are FTA in this list can be viewed like channel 613.

I don't understand as when I look to both logs the parameters looks the same. Do you?

Here's the debug log of the other network ID.
[Enigma2-debug-20200812_15-29-17.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/5068147/Enigma2-debug-20200812_15-29-17.zip)

**Comment by retrofan1979** [comment]
As workaround for now I do a channelscan of the first network ID and then insert one channel from the other netwerk ID to the first netwerk ID. However, I hope you can fix this issue very soon, so this isn't needed anymore. ;-)

**Comment by AbuBaniaz** [comment]
Can you please confirm the recording you provided earlier was on the home transponder/frequency for the NetID?

In response to the earlier question, yes Transedit is fine.

**Comment by retrofan1979** [comment]
Hi, yes  recording was done from the home frequency of the Network ID. I used TransEdit but I don't know if it went okay.

**Comment by retrofan1979** [comment]
I'm sorry, but I cannot record the home frequency with NIT tables. Maybe my hardware doesn't support it.
The debug files aren't enough to fix this issue?

**Comment by retrofan1979** [comment]
I also saw the <custom transponders> entry in the provider xml for DVB-T UK. Does it also work with DVB-C? And how?

**Comment by retrofan1979** [comment]
I also tried dvbsnoop with option -s ts -tsraw -b > capture.ts when tuning the home frequency.
and get this:
Error (122 ): DMX_SET_PES_FILTER failed: Operation not supported
Or can I try another command with dvbsnoop?

**Comment by AbuBaniaz** [comment]
ABM reads tables, it does not interrogate frequencies

One of the ABM developers said the recording was on the incorrect frequency and that you are using old NetID. It is also possible that the the encryption flag is wrong.

If you receiver is capable, you could try getting a recording with this:
https://github.com/oe-alliance/AutoBouquetsMaker/tree/tools/scripts%20and%20tools/Stream%20recording

**Comment by retrofan1979** [comment]
> ABM reads tables, it does not interrogate frequencies
> 
> One of the ABM developers said the recording was on the incorrect frequency and that you are using old NetID. It is also possible that the the encryption flag is wrong.
> 
> If you receiver is capable, you could try getting a recording with this:
> https://github.com/oe-alliance/AutoBouquetsMaker/tree/tools/scripts%20and%20tools/Stream%20recording

I will try the tool, but the recording was taken from the correct frequency. Otherwise I didn't have signal ;-) My cable provider uses the NetID for other purposes. NetID 4444 is for FTA channels and NetID 5555 for people with a subscription for encrypted channels including the FTA onew.

As far as I can see in the debug logs both NetID's have the correct FTA flag as well.
Maybe I can get in touch with the ABM developers? 
The cableplugin does read frequencies instead of tables? So that's why it finds the missing channel of ABM?

**Comment by retrofan1979** [comment]
![Knipsel1](https://user-images.githubusercontent.com/30625590/90328608-f0bd0380-df9d-11ea-8eab-d403ef72ee09.PNG)

![Knipsel2](https://user-images.githubusercontent.com/30625590/90328610-f3b7f400-df9d-11ea-9d6a-f90655df0faf.PNG)

**Comment by retrofan1979** [comment]
As you can see TransEdit does find the LCN correctly. In the first picture the LCN isn't filled in, because the program wants me to select te Network ID first. I tried them all and I get the correct LCN of 613 back with all Network ID's.
As you can see Network ID 4444 is for FTA channels and 5555 for all channels. The 43xxx range are old Network ID's, but they still work for compatibility.

**So, it seems a bug in ABM as both TransEdit and the Enigma2 cableplugin do find the LCN of this channel.**

Maybe the field TPID (not TSID) or Language can be the fault for this issue in ABM?

**Comment by retrofan1979** [comment]
> ABM reads tables, it does not interrogate frequencies
> 
> One of the ABM developers said the recording was on the incorrect frequency and that you are using old NetID. It is also possible that the the encryption flag is wrong.
> 
> If you receiver is capable, you could try getting a recording with this:
> https://github.com/oe-alliance/AutoBouquetsMaker/tree/tools/scripts%20and%20tools/Stream%20recording

Unfortunately not possible with my receiver.

**Comment by retrofan1979** [comment]
Here's the source code of the cablescan plugin. Don't know if it's useful for you:

https://github.com/OpenViX/enigma2/blob/master/lib/python/Plugins/SystemPlugins/CableScan/plugin.py

**Comment by retrofan1979** [comment]
I also see this error in de debug log: Above service not in LCN dict
However, the channel is found with the correct LCN.
Maybe to let ABM act the same with this error: not in service_dict_tmp

**Comment by retrofan1979** [comment]
Last suggestion. Otherwise I don't know what it could be.

In the provider config file I see that as protocol LCN is mentioned, but I also see "lcn2", "lcnbat", "lcnbat2", "nolcn", "sky", "vmuk".
The last 3 aren't suitable, but what about the first 3? However, I don't know the differences.

Now, I'm waiting you guys have fixed this issue. ;-)

**Comment by retrofan1979** [comment]
I will get an USB tuner tomorrow. I hope I can provide a complete recording with this and you guys can fix this issue with help of this recording.

**Comment by retrofan1979** [comment]
Succes! With a Terratec TC2 USB tuner I was able to record the complete TS stream from the home frequency.
Please search for TSID 2051 at 834.75 MHz. The LCN is 613 which is correct.
Why doesn't it show up in my channellist like the cablescan plugin does?
Hope you now finally can fix this issue. Thank you!

https://www.dropbox.com/s/r0nig56zak2t3uo/Ziggo%20164%2008-20%2013-17-12.zip?dl=0

**Comment by AbuBaniaz** [comment]
This is the response from one of our developers

```
As I am not aan Ziggo customer, it is difficult for me to test.
I understand he is using an 'old' netid for Ziggo (4444).
The ts file for that netid is recorded on the wrong frequency. This file does not contain the correct information.
As far as I understand Ziggo has now 1 netid (5555) for all their networks, also the old UPC networks.
When he is using this netid and that 1 channel 613 is missing, we need a recording of the home channel freq we are using for netid 5555.
Then I can have a look at it.

As I understand he only wants the FTA channels. It is possible that Ziggo has the subscription flag on 613, but free to watch.
```

Please get a recording of 474000

**Comment by retrofan1979** [comment]
How can I contact the developer directly? It's very difficult to communicate this way.
As Ziggo customer I know all the details.

**Comment by retrofan1979** [comment]
Ofcourse, here it is.

https://www.dropbox.com/s/ywyvhn3k8ohkrhy/Ziggo%20164%2008-20%2013-56-11.zip?dl=1

**Comment by Huevos** [comment]
Change protocol to "vmuk2".

**Comment by Huevos** [comment]
Also, possibly "lcn2" as it looks like 0x83 is present in NIT, and just 0x41 is missing.

Anyway, try both and see what result you get.

**Comment by retrofan1979** [comment]
Hi, great, that did the trick. When I set the protocol to lcn2, the issue is fixed, finally. ;-) Very easy!
But what should we do for cable_nl.xml? Can we set it to lcn2 without problems for all providers including Ziggo?

**Comment by AbuBaniaz** [comment]
We'll have to split it as far as I am aware. We can rename the section to Ziggo too.

**Comment by retrofan1979** [comment]
Okay, thanks!

**Comment by AbuBaniaz** [comment]
The NetIDs are as follows:
```
		 1536 - Ziggo Network
		 3333 - HE Heerenveen B2B FTA
		 4444 - HE Heerenveen FTA
		 5555 - HE Heerenveen
		 6666 - HE Heerenveen B2B

		 43136 - HE Amsterdam
		 43138 - HE Lelystad
		 43140 - HE Heerenveen
		 43142 - HE Zevenaar
		 43144 - HE Helmond
		 43146 - HE Rotterdam
```

Please check and tidy up this file and re-upload.
[cable_nl_ziggo.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/5120239/cable_nl_ziggo.zip)

**Comment by retrofan1979** [comment]
Here's the updated cable_nl_ziggo.xml. The 43xxx range are old NetIDs. The new ones are 4444 and 5555 for customers and 3333 and 6666 for business partners. 1536 is the internal network of Ziggo and not useable.

[cable_nl_ziggo.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/5125485/cable_nl_ziggo.zip)

**Comment by retrofan1979** [comment]
Hmmm, I guess NetID 3333 and 6666 are also old NetID's as they aren't menioned anymore when I follow the wizard for business partners to install TV. Only 4444 and 5555 are mentioned. So, please remove those as well from the file.

**Comment by Huevos** [comment]
How do we know this works in other regions?

**Comment by retrofan1979** [comment]
Please read this again (let Chrone translate the site): https://www.techconnect.nl/blog/2217/ziggo-digitaal-kijken-zonder-module/amp/

**Comment by retrofan1979** [comment]
Issue is fixed and a separated config file for Ziggo is created using LCN2 protocol.
