### ISSUE TITLE
Update for cable_nl.xml

### ISSUE THREAD

**Issue by retrofan1979** [oe-alliance/AutoBouquetsMaker#158]
Added: Ziggo network ID 4444 - former UPC, unencrypted channels

Please update your file. Thank you!

**Comment by retrofan1979** [comment]
[cable_nl.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/5046850/cable_nl.zip)

**Comment by AbuBaniaz** [comment]
Isn't this suffficient?
https://github.com/oe-alliance/AutoBouquetsMaker/blob/master/AutoBouquetsMaker/providers/cable_nl.xml#L44

**Comment by retrofan1979** [comment]
Hi, no, although my region uses the same network ID for FTA channels, it uses another scan frequency. Frequency 474 MHz doesn't give any channels.
So, that's the reason for completing this list.
Actually, the same goes for network ID 5555.
Frequency 474 is for Ziggo and frequency 164 MHz is for Ziggo former UPC.
UPC was another cable provider but is merged with Ziggo some years ago.

**Comment by retrofan1979** [comment]
Here's an updated file with both network ID 4444 and 5555 for Ziggo former UPC area.
[cable_nl.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/5051011/cable_nl.zip)

**Comment by retrofan1979** [comment]
If you want you can update the provider profile on the server, but for now i'm closing this thread so you can focus on more important issues like a missing channel ;:)
