### ISSUE TITLE
Option not to show provider name and section name

### ISSUE THREAD

**Issue by retrofan1979** [oe-alliance/AutoBouquetsMaker#159]
Hi,

Is there a possibility to hide provider name and section name after a channelscan?
The prefix of provider can be disabled, but channel 0 remains in the scanned bouquet.

Or can I simply delete sections part from provider file?

Thanks!

**Comment by AbuBaniaz** [comment]
Provider name is a config item. Default is off, so you must have enabled it.
Sections: If you don't want the section names, how would the bouquets/sections be named? You cant have bouquets with no name Best you do not create sections and just have one large section/bouquet.

**Comment by retrofan1979** [comment]
Yes, indeed, the prefix of provider was enabled, I now disabled it.
However, the channellist still starts with the line 'Kanaal lijst' which I don't want to be displayed.
I can manually remove this entry after the channelscan, but how can I remove this setting in the provider config file?
When removing the sections tag in the prover config file, the provider cannot be selected anymore in ABM.
The bouquet indeed has the name of the provider.

**Comment by retrofan1979** [comment]
I tried to delete channel 0 (marker) with use of CustomMix file, but it doesn't work unfortunately...
Now I have to manually delete it in Bouquets Editor of OpenWebIF.

**Comment by AbuBaniaz** [comment]
I don't understand what you mean. Please post a screenshot to explain what you mean.

**Comment by retrofan1979** [comment]
Here are the screenshots the way the cablescan plugin does. This is what I prefer ABM should do.
Bouquets name is not all channels but has the provider name and the channellist begins with channel 1 without name of provider.

![20200817_192652](https://user-images.githubusercontent.com/30625590/90426480-6a99dd80-e0c1-11ea-8c3d-f12aff819c09.jpg)

![20200817_192820](https://user-images.githubusercontent.com/30625590/90426513-784f6300-e0c1-11ea-93df-1ad7cb4e7b02.jpg)

**Comment by AbuBaniaz** [comment]
Please post screenshot of ABM. Thank you.

**Comment by retrofan1979** [comment]
> Please post screenshot of ABM. Thank you.

![20200818_072829](https://user-images.githubusercontent.com/30625590/90476184-47a31400-e129-11ea-9029-5927aaa5375d.jpg)

**Comment by retrofan1979** [comment]
![20200818_071801](https://user-images.githubusercontent.com/30625590/90476249-6b665a00-e129-11ea-9552-cf9cd23c2e50.jpg)

**Comment by retrofan1979** [comment]
Do you now understand my question with help of these pictures?
Hope you can add an option for this in ABM. Thank you!

**Comment by AbuBaniaz** [comment]
Just to calrify,  you want it to say `Ziggo` instead of `All Channels`? 
So what happens if someone enables provider name. Instead of `Ziggo All channels`, it will say `Ziggo -Ziggo`.

For now you can just rename the section in the provider file to say `Ziggo`

I still don't know what you mean by channel 0. None of your screenshots show it. P.S you can get a bettre screenshot by posting the following in your web browser:
`http://192.168.0.25/grab?format=jpg&mode=osd`
Change the IP address to match your receiver.

**Comment by retrofan1979** [comment]
Channel 0 is not a real channel, but a marker at position 0 if I look in the Bouquetseditor of OpenWebIF. Just try for yourself.
For now I indeed will do a manual adjustmsnt.

**Comment by retrofan1979** [comment]
I don't want to see the text "Kanaal lijst" when I open the channellist. Is this possible? Can ABM skip the marker?
Indeed we have nothing to do with OWIF ;-)

<sections>
	<section number="1">Kanaal lijst</section>
</sections>

**Comment by AbuBaniaz** [comment]
It is the section name. I told yo what to change already.

**Comment by retrofan1979** [comment]
Yes, you wrote this, but don't know how to do this. Can you explain?

Best you do not create sections and just have one large section/bouquet.

**Comment by retrofan1979** [comment]
Yes, that's indeed an alternative, but actually I don't want to see a section name at all when the channellist is opened with UP key.
Anyway, if this isn't possible, it's too bad. I wanted to have it the same way as the cablescan plugin does.

**Comment by retrofan1979** [comment]
I close this issue because it's not possible to hide the section name in the channellist.

**Comment by retrofan1979** [comment]
Just to clarify. Is it possible to get the channellist this way, see picture 2. Then I know it for sure. Thank you.

Now, it shows it this way.

![1_0_19_4BC9_832_600_FFFF0000_0_0_0_20200828114100](https://user-images.githubusercontent.com/30625590/91547473-42fa0f00-e924-11ea-9270-3f03c1f8ecb7.jpg)

![1_0_19_4BC9_832_600_FFFF0000_0_0_0_20200828113432](https://user-images.githubusercontent.com/30625590/91547479-455c6900-e924-11ea-9579-b5b2bd0231bc.jpg)
