### ISSUE TITLE
Itv ppv HD not showing up on virgin uk hd channels bouquet 

### ISSUE THREAD

**Issue by davesayers2014** [oe-alliance/AutoBouquetsMaker#16]
I noticed that ITV PPV HD isn't showing up on virgin uk hd bouquet is there a work around for this it's like abm isn't noticing it as an hd channel.

**Comment by AbuBaniaz** [comment]
Closed by
https://github.com/oe-alliance/AutoBouquetsMaker/commit/1ecf77f0d4de8ebcf4f9f2fc5939bed383b2b679
