### ISSUE TITLE
Combining multiple network ID's to 1 bouquet

### ISSUE THREAD

**Issue by retrofan1979** [oe-alliance/AutoBouquetsMaker#160]
Is it also possible to combine more network ID's from one provider to 1 bouquet?
For example: netid="1111";"2222"
Sometimes this could be handy.
If not possible, please consider to add this feature.
Thank you!

**Comment by AbuBaniaz** [comment]
The whole point is to filter and only keep one Network ID, where you are located. Otherwise how do you deal with situation where you have two different services on one LCN. Or same service with different tuning parameters.

**Comment by retrofan1979** [comment]
Okay, yes, I see, you're right.
I'm closing this thread.
