### ISSUE TITLE
ABM plugin for DVBViewer Pro for channelscan?

### ISSUE THREAD

**Issue by retrofan1979** [oe-alliance/AutoBouquetsMaker#161]
I saw there's a fastscan plugin for DVBViewer Pro to scan DVB-S transponders:
http://www.ab-forum.info/viewtopic.php?t=61217&start=120

Is something similar possible for DVB-C?
An ABM plugin to scan DVB-C channels inside DVBViewer Pro?

**Comment by AbuBaniaz** [comment]
ABM only works on Enigma2
