### ISSUE TITLE
Saorsat changes July 2020

### ISSUE THREAD

**Issue by Adrianmck** [oe-alliance/AutoBouquetsMaker#168]
Saorsat changed setting on the 1st of July 2020

https://www.2rn.ie/broadcast/saorsat-digital-television/

The new settings are 
Frequency 20192.5MHz
Symbol rate 12500
FEC 5/6

**Comment by AbuBaniaz** [comment]
So it looks like the initial details we were using were wrong anyway.

I have just made the changes  but can't test them. If the new file does not work, can you modify the file and upload the corrected version?

Details here:  
https://github.com/oe-alliance/AutoBouquetsMaker/blob/master/AutoBouquetsMaker/custom/README.txt#L449:L485

**Comment by AbuBaniaz** [comment]
It has been over a week since the changes were made. I am closing this issue now. Please re-open if needed.
