### ISSUE TITLE
Error scan sat_3550_bistv.xml

### ISSUE THREAD

**Issue by patsavatv** [oe-alliance/AutoBouquetsMaker#169]
hello,
operating error of transponder
file: AutoBouquetsMaker/AutoBouquetsMaker/providers/sat_3550_bistv.xml
modification of the FEC on transponder, the new settings are FEC 2/3
line 10 , replace   fec_inner="3"  through  fec_inner="2"
thank you

**Comment by patsavatv** [comment]
The new settings are FEC 2/3

**Comment by AbuBaniaz** [comment]
Please attach the corrected provider file. Github will not accept .xml files, so create zip file first.

**Comment by patsavatv** [comment]
[sat_3550_bistv.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/5634922/sat_3550_bistv.zip)
Hello,
Please find attached the corrected supplier file.
