### ISSUE TITLE
Error Scan on 45°E: Vivacom package

### ISSUE THREAD

**Issue by morpheus883** [oe-alliance/AutoBouquetsMaker#184]
Vivacom package on 45°E isn't working: reference frequency 11513V is now empty!

Morph

**Comment by morpheus883** [comment]
New sat_450_vivacom.xml:
[sat_450_vivacom.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/7792291/sat_450_vivacom.zip)

**Comment by AbuBaniaz** [comment]
Is it OK to close this now?

**Comment by morpheus883** [comment]
Yes, thank you!
