### ISSUE TITLE
Sky main event hd

### ISSUE THREAD

**Issue by V0dka25** [oe-alliance/AutoBouquetsMaker#186]
Sky main event hd doesnt work in the bouqet but works in the all channel, i have moved the channel but every time it rescans i lose it 

i have found the sat_282_sky_uk.xml

Just not sure what i need to change if anyone can help

**Comment by AbuBaniaz** [comment]
If you can still decrypt this service, please post back/re-open the issue and we will look at it. I will close this for now.
