### ISSUE TITLE
UK Freeview Sandy Heath COM7 frequency wrong

### ISSUE THREAD

**Issue by flanzm** [oe-alliance/AutoBouquetsMaker#187]
Frequency of COM7 HD MUX should be 746MHz (see https://ukfree.tv/transmitters/tv/Sandy_Heath)

**Comment by AbuBaniaz** [comment]
ABM reads the data in the tables on the signal stream.  We have overrides in place to correct errors/issues as well as listing HD muxes. What do you need to override?

https://github.com/oe-alliance/AutoBouquetsMaker/blob/master/AutoBouquetsMaker/providers/terrestrial_uk_freeview.xml#L216:L217

**Comment by flanzm** [comment]
Sorry need to change HD custom transponder line that says

<customtransponder key="sandy_heath________" frequency="562000000" transport_stream_id="a000" system="1"/>

to

<customtransponder key="sandy_heath________" frequency="746000000" transport_stream_id="a000" system="1"/>

Have changed locally and HD channels on COM7 now work - previously they didn't work.

Thanks

Mike

**Comment by AbuBaniaz** [comment]
@flanzm 
I had to update sandy heath using details from somebody's receiver when they used Frequency finder. Please post back if more tweaks required.

https://github.com/oe-alliance/AutoBouquetsMaker/commit/1f050c868355415b91571540e5d54f9c6121280c
