### ISSUE TITLE
HD_ALLOWED_Types

### ISSUE THREAD

**Issue by jas0npc** [oe-alliance/AutoBouquetsMaker#19]
ABM started to cause zgemma h2s to error and reboot, attached is a pic, hope this helps to fix it.
![16492228_10210057020795220_595389400_o](https://cloud.githubusercontent.com/assets/13608254/22627206/27bb1db6-ebb6-11e6-8f65-9c53547095e7.jpg)

**Comment by davesayers2014** [comment]
Have you ran a software update? Have a look here http://www.world-of-satellite.com/showthread.php?55352-Abm-attributes-error-HD_ALLOWED_TYPES

**Comment by AbuBaniaz** [comment]
Please use config files to match your version of ABM. If you want to use latest config files, you need to be using latest ABM.
