### ISSUE TITLE
28.2e ITV Yorkshire Regions

### ISSUE THREAD

**Issue by itstelboy** [oe-alliance/AutoBouquetsMaker#197]
The Yorkshire regional settings tune the  ITV channel incorrectly to Granada for the SD channel, but the HD channel is tuned correctly to Yorkshire TV.

**Comment by AbuBaniaz** [comment]
They have closed some services.

https://helpforum.sky.com/t5/Sky-TV/ITV-SD-closes-on-13-April/ba-p/3661715

**Comment by AbuBaniaz** [comment]
Use the HD region now to get the correct Regional ITV version. Alternatively, use the custom mix file to create an ITV bouquet with all the different regional ones.

https://www.world-of-satellite.com/showthread.php?47016-ABM-Hacks-Examples&p=365724&viewfull=1#post365724
