### ISSUE TITLE
can AMC BT HD be removed from the channel swap please?

### ISSUE THREAD

**Issue by davesayers2014** [oe-alliance/AutoBouquetsMaker#21]
HI can AMC BT HD be removed from the HD channel swap please im having issues swapping it for the sd version using  custommix.xml with my area hd with channel  swap to yes. This channel is currently unavailable on sat via enigma2 boxes and isnt available on cable so I couldn't see an issue removing it from the swap. If this isnt possible could I have a solution for swapping it via custommix and deleting the HD version thanks 

https://github.com/davesayers2014/AutoBouquetsMaker/blob/master/AutoBouquetsMaker/custom/sat_282_sky_uk_CustomMix.xml

**Comment by AbuBaniaz** [comment]
Closed with this
https://github.com/oe-alliance/AutoBouquetsMaker/commit/859c6ef5cc0df3993eb52308601a1894df270b22

**Comment by davesayers2014** [comment]
Thank you I will test later

**Comment by davesayers2014** [comment]
That works fine thanks
