### ISSUE TITLE
cable_uk_virgin.xml channel swap has duplicate albia hd swaps

### ISSUE THREAD

**Issue by davesayers2014** [oe-alliance/AutoBouquetsMaker#23]
I'm not sure how long this has been in the swap but there is 2 swaps for alia HD. Swap for 200 and 130 needs removing as it is overwriting albia+1 and is causing a cycle loop in channel selection between 126 and 129

**Comment by davesayers2014** [comment]
Just an update on this the correct swap was added here https://github.com/oe-alliance/AutoBouquetsMaker/commit/54d7ccaba5e45a20f11068a27d1b73feb6a54e73 but the old swap wasn't removed. I removed the 130 swap and albia+1 was available on 130 and no cycle loop has occurred

**Comment by AbuBaniaz** [comment]
Thanks.
