### ISSUE TITLE
Few changes on sky uk

### ISSUE THREAD

**Issue by yannydodo12** [oe-alliance/AutoBouquetsMaker#231]
channel number="152" with="836"/> <!-- Sky Sci-Fi HD 
channel number="155" with="846"/> <!-- YESTERDAY HD 
channel number="423" with="876"/> <!-- BT Sport4 HD 
                5382: "BT Sport 6",
		5383: "BT Sport 7",
		5384: "BT Sport 8",
		5385: "BT Sport 9",
		5386: "BT Sport 10",

**Comment by AbuBaniaz** [comment]
Before:
![bt sport existing](https://user-images.githubusercontent.com/6644489/184548526-d6bdb18f-73f5-44bf-be6b-016a06216043.jpg)

After:
![bt sport after](https://user-images.githubusercontent.com/6644489/184548553-4a89d727-2405-4613-9b3c-4084d77eed47.jpg)

**Comment by yannydodo12** [comment]
Thanks mate..
