### ISSUE TITLE
few swap changes to sky uk

### ISSUE THREAD

**Issue by yannydodo12** [oe-alliance/AutoBouquetsMaker#247]
channel number="139" with="836"/> -- Sky Sci-Fi HD -->		
channel number="159" with="835"/> -- E! HD -->

also some new  Channel 4 HD channels. Can they be renamed to their area.
1250: ("Channel 4 HD", "Channel 4 Ireland HD"),
1213: ("Channel 4 HD", "Channel 4 Midlands HD"),
1249: ("Channel 4 HD", "Channel 4 North HD"),
1246: ("Channel 4 HD", "Channel 4 NI HD"),
1202: ("Channel 4 HD", "Channel 4 South & East HD"),
1248: ("Channel 4 HD", "Channel 4 Scotland HD"),

Thanks..

**Comment by AbuBaniaz** [comment]
I added those two swaps. 

I don't see any added value in adding those renames. They don't have regional programming, just regional adverts.  Only one I see point in changing is the Ireland one which is not free. Suppose that would apply to the SD one too.

**Comment by yannydodo12** [comment]
k mate thanks
