### ISSUE TITLE
sat_130_polsat_box.xml

### ISSUE THREAD

**Issue by jackzab** [oe-alliance/AutoBouquetsMaker#258]
Plis Add new provider polsat box 

<provider>
	<name>POLSATBOX</name>
	<dependent>sat_130_POLSAT_BOX</dependent>
	<streamtype>dvbs</streamtype>
	<protocol>lcn</protocol>
	<transponder
		orbital_position="130"
		frequency="11158000"
		symbol_rate="27500000"
		polarization="1"
		fec_inner="3"
		inversion="2"
		system="1"
		modulation="1"
		roll_off="0"
		pilot="2"
		tsid="1089"
		onid="1"
	/>
	<sections>
		<section number="1">POLSATBOX</section>
	</sections>
	<servicehacks>
<![CDATA[
]]>
	</servicehacks>
</provider>

**Comment by AbuBaniaz** [comment]
What is the home frequency?DO you have a copy of an official channel list (not one that somebody has compiled)? Have you tried making a file?

**Comment by AbuBaniaz** [comment]
https://github.com/oe-alliance/AutoBouquetsMaker/commit/c64dcee7329bfd1e5d18c115d737bc03b3eb750f
