### ISSUE TITLE
Sky Sports 1 ROI not working

### ISSUE THREAD

**Issue by davesayers2014** [oe-alliance/AutoBouquetsMaker#27]
using sky roi and Sky Sports 1 is not working I tried editing the sat_282_sky_irl.xml to provide a fix via add channel id and rename but I cant work it out working version is 

1301: "Sky Sports 1 UK",

I have added it via custommix and that works 

[sat_282_sky_irl_CustomMix.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/887608/sat_282_sky_irl_CustomMix.zip)

But would be best adding it to the providers file for all users

**Comment by AbuBaniaz** [comment]
This is an encryption issue, not an ABM issue.

**Comment by davesayers2014** [comment]
so you added the Irish to uk but not adding uk to Irish?

**Comment by davesayers2014** [comment]
I know this is an encryption issue but thought you would have added uk version to irl just like you did for uk adding sky sports 4 roi

**Comment by AbuBaniaz** [comment]
What on earth you on about? What is this then? https://github.com/oe-alliance/AutoBouquetsMaker/commit/785f1311ea82fe28c3c79aacc22876265327aca1

**Comment by davesayers2014** [comment]
I noticed you have made another change so tried update config files and now get this 

![image](https://cloud.githubusercontent.com/assets/17779364/24579303/70a0918c-16ea-11e7-95a1-bcb15ffcf914.png)

It could be an error my end even though my network is fine.

So I manually copied and pasted the file but it has made no change Atlantic is still there and sky sports 1 still doesnt work adding the above custommix works it maybe an issue my end apologies for the confusion

**Comment by davesayers2014** [comment]
Sorted but you only made these changes after I opened the issue. I still get the 404 error but this maybe my end thanks

**Comment by AbuBaniaz** [comment]
In light of your attitude, I won't be responding to any more of your issues

**Comment by davesayers2014** [comment]
Apologies I was only asking if they was going to be swapped like you did for uk and now you have ill close the issue sorry if I offended you
