### ISSUE TITLE
Update provider file error

### ISSUE THREAD

**Issue by escortrs** [oe-alliance/AutoBouquetsMaker#284]
Hi,
Not sure if this is the right place to ask,
I am using openATV 6.4 which is py2 and when I try to update provider file I get an error 

incompatible versions: 3.3>3.4

Is 3.3 the last py2 version or do i have another issue going on? any help would be great.

Thanks

**Comment by AbuBaniaz** [comment]
I am afraid that nobody builds from OE-A 4.2 branches that are geared for python 2 images. 
Moreover, there was a dvbreader binary file change for a 19.2 provider. A new binary wont work on ATV 6.4.
