### ISSUE TITLE
Movistar + doesnt work

### ISSUE THREAD

**Issue by javik34** [oe-alliance/AutoBouquetsMaker#290]
Today Movistar moved the lastest channels from 10729 to other TP and the scan say empty data

how to fix this.

**Comment by miberian** [comment]
Yes. Need an update to tunning params. New provider file attached. @AbuBaniaz please merge.

[sat_192_movistar_plus_esp.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/13678576/sat_192_movistar_plus_esp.zip)

**Comment by AbuBaniaz** [comment]
Thanks. I have committed the tuning/blacklist changes. Is there a website to check the home frequency details? I had a brief search earlier but could not find them.

@javik34
Please use the function within ABM to update provider file.

**Comment by miberian** [comment]
No website that I am aware of. Just check kingofsat for example: https://es.kingofsat.net/pack-digitalplusa.php

I went for the transponder with the home channel (PORTADA), which is used to download settings and tv guide (MHW2).

**Comment by javik34** [comment]
Blue screen at scan hd+sd,only work HD.

[20231215-070605-enigma2-crash.log](https://github.com/oe-alliance/AutoBouquetsMaker/files/13683154/20231215-070605-enigma2-crash.log)

**Comment by miberian** [comment]
It works for me in OpenATV 7.3 with the latest version of the plugin. You are sharing an OpenSPA log, which is stuck in an old version of the plugin that does not support a list of regions as input, which will explain why only HD is working. In fact, someone is already asking OpenSPA team for it: https://openspa.info/threads/actualizar-autobouquetsmaker.58514/

**Comment by javik34** [comment]
> It works for me in OpenATV 7.3 with the latest version of the plugin. You are sharing an OpenSPA log, which is stuck in an old version of the plugin that does not support a list of regions as input, which will explain why only HD is working. In fact, someone is already asking OpenSPA team for it: https://openspa.info/threads/actualizar-autobouquetsmaker.58514/

I the same person

**Comment by AbuBaniaz** [comment]
There are other python/reader files needed for the latest provider files. This is why we increased the version number to prevent people updating to it.

Here is an older provider file with just the tuning frequencies changed. It will not have the correct/full channel list for Movistar though.

[sat_192_movistar_plus_esp.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/13686806/sat_192_movistar_plus_esp.zip)

What version of python is your image using?

**Comment by javik34** [comment]
> There are other python/reader files needed for the latest provider files. This is why we increased the version number to prevent people updating to it.
> 
> Here is an older provider file with just the tuning frequencies changed. It will not have the correct/full channel list for Movistar though.
> 
> [sat_192_movistar_plus_esp.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/13686806/sat_192_movistar_plus_esp.zip)
> 
> What version of python is your image using?

Python 3.11.2 (main, Feb  7 2023, 13:52:42) [GCC 12.2.0] on linux

**Comment by AbuBaniaz** [comment]
Try installing this version

[enigma2-plugin-systemplugins-autobouquetsmaker_3.4+git1053+690d6ae-r0_cortexa15hf-neon-vfpv4.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/13687433/enigma2-plugin-systemplugins-autobouquetsmaker_3.4%2Bgit1053%2B690d6ae-r0_cortexa15hf-neon-vfpv4.zip)

**Comment by javik34** [comment]
> Try installing this version
> 
> [enigma2-plugin-systemplugins-autobouquetsmaker_3.4+git1053+690d6ae-r0_cortexa15hf-neon-vfpv4.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/13687433/enigma2-plugin-systemplugins-autobouquetsmaker_3.4%2Bgit1053%2B690d6ae-r0_cortexa15hf-neon-vfpv4.zip)

Ok, try and later reply. Thanks.

**Comment by javik34** [comment]
> Try installing this version
> 
> [enigma2-plugin-systemplugins-autobouquetsmaker_3.4+git1053+690d6ae-r0_cortexa15hf-neon-vfpv4.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/13687433/enigma2-plugin-systemplugins-autobouquetsmaker_3.4%2Bgit1053%2B690d6ae-r0_cortexa15hf-neon-vfpv4.zip)

![image](https://github.com/oe-alliance/AutoBouquetsMaker/assets/153848617/2738a06d-b6d7-49bc-a829-204ca570de5c)

**Comment by AbuBaniaz** [comment]
There is a `.2.ipk` at end of the ipk you are trying to install. Please double check the ipk you downloaded/transferred.  It should be named `enigma2-plugin-systemplugins-autobouquetsmaker_3.4+git1053+690d6ae-r0_cortexa15hf-neon-vfpv4.ipk` Maybe download to a new folder

**Comment by javik34** [comment]
> Try installing this version
> 
> [enigma2-plugin-systemplugins-autobouquetsmaker_3.4+git1053+690d6ae-r0_cortexa15hf-neon-vfpv4.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/13687433/enigma2-plugin-systemplugins-autobouquetsmaker_3.4%2Bgit1053%2B690d6ae-r0_cortexa15hf-neon-vfpv4.zip)

working now, yupiiii!!

**Comment by AbuBaniaz** [comment]
@miberian 
"Esp" removed from provider name.
