### ISSUE TITLE
Is it possible to add Bulsatcom at 39E

### ISSUE THREAD

**Issue by k-otixxx** [oe-alliance/AutoBouquetsMaker#292]
Is it possible to add provider Bulsatcom at 39 E Hellas Sat.
Frequency DVB-S 12271 30000 7/8 is NIT .
Bulsatcom is bulgarian TV operator like Vivacom on 45 E.

**Comment by AbuBaniaz** [comment]
Is there an official channel list? Are you able to make a provider file and see if ABM output is correct?

**Comment by k-otixxx** [comment]
When i replace the file for Telecom Romania with parameters for Bulsatcom, ABM work, but without LCN numbering.
[sat_390_bulsatcom.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/13907245/sat_390_bulsatcom.txt)

This is official channels list for enigma2 (work with Dreamset-editor):
https://mega.nz/file/5ToBjJoL#syiO6CHTqVcXwUF2cQy_GHlzlggztcbiJjNhXhuTyPc

**Comment by AbuBaniaz** [comment]
It might be using a different protocol.

Can you get a raw stream recording on the home transponder?  Tools are here, hopefully will work on your receiver.
https://github.com/oe-alliance/AutoBouquetsMaker/tree/tools

**Comment by k-otixxx** [comment]
I have TBS 5980 CI ,this is TS file from 12271 

https://mega.nz/file/lCQ0XYxA#SealOxvj4I6kKm1BHlRcLx-KjafpTNx7nIFck7xgUng

**Comment by k-otixxx** [comment]
When i was modified file for Telekom romania with LCN protocol, instead lcnbat , channels are OK with lcn arange.
`
<provider>
	<name>Bulsatcom</name>
	<streamtype>dvbs</streamtype>
	<protocol>lcn</protocol>
	<transponder
		orbital_position="390"
		frequency="12271000"
		symbol_rate="30000000"
		polarization="0"
		fec_inner="5"
		inversion="2"
		system="0"
		modulation="1"
		roll_off="0"
		pilot="2"
		tsid="1"
		onid="1"
	/>
	<dvbsconfigs>
		<configuration key="sd_24704" bouquet="0x6080" region="0xe2">Bouquet 1</configuration>
		<configuration key="sd_24705" bouquet="0x6081" region="0xe2">Bouquet 2</configuration>
		<configuration key="sd_24919" bouquet="0x6157" region="0xe2">Bouquet 3 (NewCardOnly)</configuration>
	</dvbsconfigs>
	<sections>
		<section number="1">Bulsatcom</section>
	</sections>
	<servicehacks>
<![CDATA[
]]>
	</servicehacks>
</provider>

`
