### ISSUE TITLE
Cyrillic characters in channel's name problem , after scanning 45E Vivacom.

### ISSUE THREAD

**Issue by k-otixxx** [oe-alliance/AutoBouquetsMaker#294]
After scanning Vivacom at 45E , cyrillic channel names -unrecognised!
15 channels  at 4 transponders(11475V,12520V,12560V,12600V) on Vivacom DTH 45 East.
After zapping on transponder , names are corrected, but is annoying to see unrecognised symbols, instead correct channel name in cyrillic.
Names in lamedb and lamedb5 are also in these unrecognised symbols.
Channels with latin names and EPG are not affected!

**Comment by k-otixxx** [comment]
![1_0_1_67_1_D5_1C20000_0_0_0_20240205200124](https://github.com/oe-alliance/AutoBouquetsMaker/assets/38030395/7bdb53e2-f3fc-48aa-9477-e49b0ab2ecca)
![1_0_1_D1_2_D5_1C20000_0_0_0_20240205200207](https://github.com/oe-alliance/AutoBouquetsMaker/assets/38030395/7dc43e74-87db-433f-8e9f-d3cc91754584)

**Comment by k-otixxx** [comment]
Is it possible to add iso 8859-5 in ABM code, because of the problem with cyrillic letters above?

**Comment by AbuBaniaz** [comment]
These commits added for the issue
https://github.com/oe-alliance/AutoBouquetsMaker/commit/032182071ab25689f3068bbbc78ab86c7714d268
https://github.com/oe-alliance/AutoBouquetsMaker/commit/512834d62b5930442e1716c0d593bf6bce80fa51
