### ISSUE TITLE
Add provider Vivacom at new position 13E.

### ISSUE THREAD

**Issue by k-otixxx** [oe-alliance/AutoBouquetsMaker#297]
Please add new position of  Vivacom on 13E.
At the end of the 2024 Vivacom will migrate to the new position 13E and signal on 45E will be shut down!

sat_0130_vivacom.xml

https://mega.nz/file/9fRRnIBb#Oeu7k1FJtxKJ0A5Hozbv3EMKhIu55u3ttWWxKsIhQjo

**Comment by k-otixxx** [comment]
Here debug logs and examples files for 13E Vivacom:

https://mega.nz/file/xa4wFSxR#16l-Oe0BzfO_oVn-vuPjLKocMO1pcKxv-2jCrOBqQTA

**Comment by k-otixxx** [comment]
Corrected files above!

**Comment by AbuBaniaz** [comment]
Uploaded here for easier reference:

[Enigma2_debug_2024-05-15_22-25-30.log.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/15334606/Enigma2_debug_2024-05-15_22-25-30.log.txt)

[EXAMPLE_sd_sat_0130_vivacom_CustomLCN.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/15334609/EXAMPLE_sd_sat_0130_vivacom_CustomLCN.zip)
