### ISSUE TITLE
Test Mtel

### ISSUE THREAD

**Issue by ikosk** [oe-alliance/AutoBouquetsMaker#34]
I'm testing Mtel, but I have a problem. The programs are read only from one transponder. Please help.

> <provider>
	<name>Mtel</name>  
	<streamtype>dvbs</streamtype>
	<protocol>lcnbat</protocol>
	<transponder
		orbital_position="160"
		frequency="11595000"		
		symbol_rate="30000000"
		polarization="1"
		fec_inner="4"
		inversion="2"
		system="1"
		modulation="2"
		roll_off="0"
		pilot="2"
    bat_pid="0x11"
	/>
	<sections>
		<section number="1">Mtel</section>
	</sections>
	<dvbsconfigs>
    <configuration key="hd_1" bouquet="0x1" region="0x83" namespace="0xe080000">Mtel</configuration>
	</dvbsconfigs>
	<servicehacks>
<![CDATA[
]]>
	</servicehacks>
</provider>

**Comment by AbuBaniaz** [comment]
Do you have a link to an official channel list? Not a third party one. The file works, but there are gaps.

Also, can you change filename to "sat_0160_mtel.xml".  All new providers are being named with 4 digit orb positions.

Thanks

**Comment by ikosk** [comment]
No, I do not have a link. Can you edit the file so it works? Please :)

**Comment by ikosk** [comment]
I have xml BAT file from transponder stream.

**Comment by AbuBaniaz** [comment]
How do we know if the created list is correct? We need to compare with something.

This is the output with your file.
![1](https://cloud.githubusercontent.com/assets/6644489/26161856/01ebfca2-3b1d-11e7-944a-ff5281d3bcf9.jpg)

![2](https://cloud.githubusercontent.com/assets/6644489/26161870/0ce730e0-3b1d-11e7-9a9e-3f23d22ff2b2.jpg)

![3](https://cloud.githubusercontent.com/assets/6644489/26161880/126d3654-3b1d-11e7-81d7-10ecf2e4e7e8.jpg)

**Comment by ikosk** [comment]
Script only read programs from one transponder - 11 595 MHz. I send BAT file.

[bat.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/1008262/bat.txt)

**Comment by AbuBaniaz** [comment]
Note to self:
```
http://en.kingofsat.net/pack-mtel.php
```

**Comment by ikosk** [comment]
I created a second file tp 11554 MHz. Script search new channel. It is possible to search only SID 1803, 1804, 1805, 1817, 1820 and 1837 from 11554 MHz?


[sat_160_mtel2.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/1009826/sat_160_mtel2.txt)

**Comment by ikosk** [comment]
AutoBouquetsMaker does not support it on position 16°E? Mtel, VIPnet, Flix, ANTIK Sat do not work. Scan only first transponder.

**Comment by AbuBaniaz** [comment]
Can you get screenshots of channel layout on official receiver please?

**Comment by ikosk** [comment]
FLix TV CZ on 16E. I will send screen.
[sat_160_flix_tv_cz.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/1011930/sat_160_flix_tv_cz.txt)

**Comment by ikosk** [comment]
Flix TV CZ screen - official receiver
![img_0567](https://cloud.githubusercontent.com/assets/6972490/26218382/13d9be7e-3c0b-11e7-84fd-eb1ed2e0580b.JPG)

**Comment by ikosk** [comment]
bat_pid="0x11"
bouquet="0x2"
region="0x83" (Logical Channel number)

**Comment by ikosk** [comment]
Any idea to make it work?

**Comment by ikosk** [comment]
NIT does not work on 16E.
