### ISSUE TITLE
enable / disable all providers

### ISSUE THREAD

**Issue by ikosk** [oe-alliance/AutoBouquetsMaker#42]
Could it be added to the menu? Option to enable / disable all providers.

**Comment by AbuBaniaz** [comment]
The providers are offered based on tuner configuration. If a person has a Terrestrial tuner, he will be offered the UK, Irish and Dutch providers. Obviously enabling all would cause a problem. Most of the providers require setting up region etc. In my view, it is not a good idea to enable all providers.

**Comment by ikosk** [comment]
It is true. I just wanted to simplify the selection of multiple providers
