### ISSUE TITLE
XML export

### ISSUE THREAD

**Issue by ikosk** [oe-alliance/AutoBouquetsMaker#43]
It is possible to export data to xml?

**Comment by AbuBaniaz** [comment]
It depends what you want. There are sample custom mix files on the forum.

**Comment by AbuBaniaz** [comment]
@ikosk 
Have you seen the files?

**Comment by ikosk** [comment]
I need: channel name and pids (video, audio ...)

**Comment by AbuBaniaz** [comment]
Have a look at this:
```
https://forums.openpli.org/topic/50899-record-complete-transport-stream/page-3#entry747316
```
