### ISSUE TITLE
Sky UK - Channel 424

### ISSUE THREAD

**Issue by chenks** [oe-alliance/AutoBouquetsMaker#54]
a new channel is launching shortly in the UK on Sky EPG 424.
you currently have Eir Sports 2 on 424.
Eir Sports 2 will need to be moved to allow the new channel to appear on 424.

https://www.freesports.tv/

**Comment by AbuBaniaz** [comment]
Thanks for reporting.

We chose that number because it was used used by one of the regions. Insets will only work when a slot is vacant. We'll have a look after launch.

Thanks for reporting.

**Comment by chenks** [comment]
its launched now

**Comment by AbuBaniaz** [comment]
Insert for  Eir Sport 2 now at 425
