### ISSUE TITLE
New platform

### ISSUE THREAD

**Issue by ikosk** [oe-alliance/AutoBouquetsMaker#58]
Hi, I tested new platform Simpli TV on 19,2°E. AutoBouquetsMaker but read only home tp. 11273 MHz. What is wrong?

**Comment by ikosk** [comment]
nobody help?

**Comment by AbuBaniaz** [comment]
`https://www.simplitv.at/fileadmin/user_upload/Simplitv/images/Landingpages/DSO_S_Stmk_OOE_Sbgld/Senderlisten/Senderliste_SAT.pdf`
