### ISSUE TITLE
Virginmedia channels no audio

### ISSUE THREAD

**Issue by babis20** [oe-alliance/AutoBouquetsMaker#60]
some of virginmedia HD channels dont have any audio PID

**Comment by AbuBaniaz** [comment]
This is not an ABM issue. Even official boxes have the problem.

**Comment by stevotk** [comment]
Only some official boxes - I'm sure if ABM devs altered the PID info in an update, we would be all good again.

**Comment by AbuBaniaz** [comment]
This is not an ABM issue. Updated images have a modification to work around the error in the transmission.
