### ISSUE TITLE
cable VM channels not working

### ISSUE THREAD

**Issue by budx5** [oe-alliance/AutoBouquetsMaker#61]
updated abm config today, then after rescannng, lost nearly all my sports hd and movies hd, and quite a few others, when i say lost, i mean they are listed in fav but not opening, staying black screen.
my upstairs box is also runing the same image openvix, all channel working up there, problem started after updating abm config today for vm.
thanks

**Comment by gav28uk** [comment]
It appears the ABM update causes problems for mgcamd and it will no longer work with those channels that have been touched by the Audio Description issue, so you see a black screen. My guess is that mgcamd is getting stuck trying to decrypt the CAID:0000 Provider:00000 entry, which will never work. The workaround is to use OSCAM as that works fine with the new ABM approach and steps over the CAID:0000 Provider:000000 channel detail.

**Comment by malkinchris** [comment]
updated fixed most channels with NAR still some channels thou with NAR and no sound

**Comment by AbuBaniaz** [comment]
This is not an ABM issue
