### ISSUE TITLE
40975 Freq Change

### ISSUE THREAD

**Issue by mtyler1983** [oe-alliance/AutoBouquetsMaker#64]
Hey Chaps. Netid 40975 has had a frequency change. can you help change this in the config so we scan this id again please. I have a Tivo so can supply the new frequency if needed just let me know what line you need. it will be the same for 40975, 40976, 40977 & 40978 i assume as we could always scan any of those 4 ID's

**Comment by AbuBaniaz** [comment]
An ABM "scan" of wrong net id  will not work.

ABM will work on any frequency you lock onto for UK cable, but NetID must be correct. we however prefer to use QAM64 as those frequencies mainly contain data.

We would need a non-ABM scan of affected areas or Nit Analyser scan to input the correct frequency. Files are on Wos forum

**Comment by mtyler1983** [comment]
Ok mate. I’ll get a Nit Analyser scan done. Struggling to find the info on WOS though. Can you point me in right direction at all? Appreciate your help with this.

**Comment by AbuBaniaz** [comment]
Just stuck the thread

http://www.world-of-satellite.com/showthread.php?38120-Logs-for-unlisted-changed-areas-(UK)&p=290811&viewfull=1#post290811

**Comment by mtyler1983** [comment]
Cheers mate, ive installed DVBsnoop on the box itself.. where will i find the extracted file "NIT_analyser.py" so i can put in /tmp/

**Comment by AbuBaniaz** [comment]
Wherever you downloaded and extracted it to on your PC

**Comment by mtyler1983** [comment]
OK im missing somthing then as the opkg just gives me an ipk, doesnt extract anything else.

**Comment by mtyler1983** [comment]
Ignore me
Long Day

**Comment by mtyler1983** [comment]
[Nit Scan 40975.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/1674899/Nit.Scan.40975.zip)

**Comment by mtyler1983** [comment]
here we go. hopefully thats all the info you need

**Comment by AbuBaniaz** [comment]
I have committed the changes. Please update config file and close issue when satisfied

**Comment by mtyler1983** [comment]
you my friend are a legend.. Thank you
