### ISSUE TITLE
40975 failing to scan 

### ISSUE THREAD

**Issue by mtyler1983** [oe-alliance/AutoBouquetsMaker#66]
Afternoon chaps, 40975 stopped scanning overnight - attached is the NIT scan files for you to check to see if anything has changed.

Many Thanks
[40975.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/1713565/40975.zip)

**Comment by AbuBaniaz** [comment]
The frequencies were updated 12 days ago to match what you have provided. The file currently has 643000 as the frequency. There have been no issues reported since then.

Please start a thread on the forum with your debug log, it may show more details.
