### ISSUE TITLE
SH4 Build of latest AutoBouquetsMaker v3.0?

### ISSUE THREAD

**Issue by anthonykelly** [oe-alliance/AutoBouquetsMaker#82]
Can anyone create a SH4 architecture (like Amiko Alien 2+) build of the latest V3.0 AutoBouquetsMaker. In particular the dvbreader.so file needs to be built for SH4. I tried using an old dvbreader.so with the latest python code and config but then ABM crashes during scan. The last version I had working was V2.8 but the V2.8 and V3.0 config files seem to be incompatible. Any advice greatly appreciated.

**Comment by anthonykelly** [comment]
Here's a crash log from running ABM v3.0 on my Amio Alien 2+ 
```Hyperion crash log

crashdate=Mon May 28 21:16:37 2018
compiledate=Dec 15 2016
skin=Elgato-HD/skin.xml
sourcedate=2016-12-14
branch=master
rev=88a777b
component=Enigma2

stbmodel=spark7162
stbmodel=spark7162
kernelcmdline=console=ttyAS1,115200 rw root=/dev/mtdblock6 rootfstype=jffs2 init=/bin/devinit coprocessor_mem=4m@0x40000000,4m@0x40400000 printk=1 ip=172.100.100.249:172.100.100.174:172.100.100.174:255.255.0.0:Enigma2:eth0:off stmmaceth=msglvl:0,phyaddr:2,watchdog:5000 nwhwconf=device:eth0,hwaddr:30:00:0A:00:58:4B Manufacture=Spark-Project STB_ID=0C:00:0A:00:00:58:4B
nimsockets=NIM Socket 0:
imageversion=version=0270201209300000


<   124.703> [eDVBPESReader] Created. Opening demux
<   124.704> [eDVBPESReader] Created. Opening demux
<   219.871> [eDVBPESReader] ERROR reading PES (fd=50): Value too large for defined data type
<   250.522> Traceback (most recent call last):
<   250.522>   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/main.py", line 510, in doScan
<   250.534>     if not self.manager.read(self.selectedProviders[self.currentAction], self.providers, self.motorised):
<   250.536>   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/manager.py", line 276, in read
<   250.539>     providers[provider_key]["servicehacks"])
<   250.540>   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/dvbscanner.py", line 1174, in updateAndReadServicesFreeSat
<   250.558>     d8[service["category_id"]] = service["description"]
<   250.561> KeyError: 'description'```

**Comment by AbuBaniaz** [comment]
Until someone provides one, easiest thing is to flash OpenATV because they have a nightly build. Download the plugin from within that image using the following command.
```
opkg download enigma2-plugin-systemplugins-autobouquetsmaker
```
You will find the plugin in /home/root

**Comment by anthonykelly** [comment]
To avoid the need to flash OpenATV. Does anyone here have OpenATV on an Amiko Alien 2 box and, if so, can you run the above command for me and share the downloaded plugin?

**Comment by AbuBaniaz** [comment]
[enigma2-plugin-systemplugins-autobouquetsmaker_3.0+git457+fb9e3f5-r0_sh4.ipk.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/2053865/enigma2-plugin-systemplugins-autobouquetsmaker_3.0.git457.fb9e3f5-r0_sh4.ipk.zip)
Hope this works for you

**Comment by anthonykelly** [comment]
Perfect! It works a treat. Thanks @AbuBaniaz !
