### ISSUE TITLE
Port Talbot 00007 tuning details

### ISSUE THREAD

**Issue by shirehorse99** [oe-alliance/AutoBouquetsMaker#91]
Net ID 0007 Port Talbot has changed from 6887 to 6952 and QAM from 64 to 256

**Comment by AbuBaniaz** [comment]
Changed here
https://github.com/oe-alliance/AutoBouquetsMaker/commit/67a08a5e7b71b93f2d0c16f71f70e1297948030a

**Comment by shirehorse99** [comment]
👍

Sent from my iPad

On 15 Nov 2018, at 00:21, AbuBaniaz <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #91<https://github.com/oe-alliance/AutoBouquetsMaker/issues/91>.
