### ISSUE TITLE
UK DVB-C Net ID 00002

### ISSUE THREAD

**Issue by chenks** [oe-alliance/AutoBouquetsMaker#93]
New details for Net ID 00002 please update in the ABM config files (FYI I have manually updated my own config files and verified settings).

QAM 256
Symbol Rate: 6952
Default Frequency: 643 Mhz

**Comment by AbuBaniaz** [comment]
Added here
https://github.com/oe-alliance/AutoBouquetsMaker/commit/3fbc78b4c0ea441e0356cf9ac752b14ab28032f3
